# new

[[manager.prepend_keymap]]
on   = [ "c", "m" ]
run  = "plugin chmod"
desc = "Chmod on selected files"

[[manager.prepend_keymap]]
on   = "T"
run  = "plugin toggle-pane max-preview"
desc = "Maximize or restore the preview pane"

[[manager.prepend_keymap]]
on   = [ "c", "h" ]
run  = "plugin toggle-pane min-preview"
desc = "Show or hide the preview pane"

[[manager.prepend_keymap]]
on   = [ "<C-g>" ]
run  = "shell lazygit --block"
desc = "lazygit"

[[manager.prepend_keymap]]
on  = "M"
run = "plugin mount"


# Goto

[[manager.prepend_keymap]]
on   = [ "g", "d" ]
run  = "cd ~/dl"
desc = "Goto ~/dl"

[[manager.prepend_keymap]]
on   = [ "g", "D" ]
run  = "cd ~/Downloads"
desc = "Goto ~/Downloads"

[[manager.prepend_keymap]]
on   = [ "g", "m" ]
run  = "cd /mnt"
desc = "Goto /mnt"

[[manager.prepend_keymap]]
on   = [ "g", "e" ]
run  = "cd /etc"
desc = "Goto /etc"

[[manager.prepend_keymap]]
on   = [ "g", "t" ]
run  = "cd ~/.local/share/Trash/files"
desc = "Goto trash"
