[manager]
ratio = [1, 3, 4]
sort_by = "modified"
sort_reverse = true
linemode = "size"

[preview]
tab_size = 4
max_width = 1280
max_height = 1280

[opener]
edit = [
    { run = '${EDITOR:=vi} "$@"', desc = "$EDITOR", block = true, for = "unix" },
    { run = 'code "$@"', desc = 'VS Code', orphan = true, for = 'unix' },
    { run = 'code "%*"', desc = 'VS Code', orphan = true, for = "windows" },
]

[plugin]
prepend_previewers = [
    { mime = "video/*", run = "video-ffmpeg" },
]

prepend_preloaders = [
    { mime = "video/*", run = "video-ffmpeg" },
]

prepend_fetchers = [
    { id = "git", name = "*", run = "git" },
]

