[mgr]
# ratio = [1, 3, 4]
sort_by = "natural"
linemode = "size"

[preview]
wrap = "yes"
max_width = 1280
max_height = 1280

[opener]
edit = [
    { run = '${EDITOR:=vi} "$@"', desc = "$EDITOR", block = true, for = "unix" },
    { run = 'code "$@"', desc = 'VS Code', orphan = true, for = 'unix' },
    { run = 'code "%*"', desc = 'VS Code', orphan = true, for = "windows" },
]



[[plugin.prepend_fetchers]]
id   = "git"
name = "*"
run  = "git"

[[plugin.prepend_fetchers]]
id   = "git"
name = "*/"
run  = "git"
